server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/exercise?serverTimezone=GMT
    username: root
    password: mysql
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/exercise?serverTimezone=GMT
          username: root
          password: mysql
        slave_1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/yk?serverTimezone=GMT
          username: root
          password: mysql
mybatis-plus:
  type-aliases-package: com.example.dynamicdatasource.Po
  mapper-locations: classpath*:mapper/*Mapper.xml